[package]
name = "xtb_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rxrust = "^1.0.0-beta.4"
thiserror = "^1.0.44"
tungstenite = "^0.20.0"
url = "^2.4.0"
