[package]
name = "xtb_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "^1.0.180", features = ["derive"] }
serde_json = "^1.0.104"
thiserror = "^1.0.44"
tungstenite = { version = "^0.20.0", features = ["rustls", "__rustls-tls"] }
url = "^2.4.0"
